name: ticktick_dbt

profile: ticktick_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  airbyte_meta_fields:
    - '_airbyte_raw_id'
    - '_airbyte_extracted_at'
    - '_airbyte_meta'
    - '_airbyte_generation_id'

  enable_gtd_work_type_categorization: "{{ env_var('ENABLE_GTD_WORK_TYPE_CATEGORIZATION', 'false') | as_bool }}"
  gtd_deep_work_tags: "{{ env_var('GTD_DEEP_WORK_TAGS', '[]') }}"
  gtd_shallow_work_tags: "{{ env_var('GTD_SHALLOW_WORK_TAGS', '[]') }}"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  ticktick_dbt:
    +schema: raw

models:
  ticktick_dbt:
    # Materialize staging models as views, and marts as tables
    +dbt-osmosis: "{parent}.yml"
    staging:
      +materialized: view
    marts:
      +materialized: view
flags:
  require_generic_test_arguments_property: true