name: ticktick_dbt

profile: ticktick_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  airbyte_meta_fields:
    - '_airbyte_raw_id'
    - '_airbyte_extracted_at'
    - '_airbyte_meta'
    - '_airbyte_generation_id'

  enable_gtd_work_type_categorization: "{{ env_var('ENABLE_GTD_WORK_TYPE_CATEGORIZATION', 'false') | as_bool }}"
  gtd_deep_work_tags: "{{ env_var('GTD_DEEP_WORK_TAGS', '[]') }}"
  gtd_shallow_work_tags: "{{ env_var('GTD_SHALLOW_WORK_TAGS', '[]') }}"
  timezone: "{{ env_var('DBT_TIMEZONE', 'UTC') }}"
  # the pipeline load interval in minutes 
  load_interval: "{{ env_var('DBT_LOAD_INTERVAL') }}"

seeds:
  ticktick_dbt:
    +schema: raw

models:
  ticktick_dbt:
    +dbt-osmosis: "{parent}.yml"
    +dbt-osmosis-options:
      force-inherit-descriptions: true
    staging:
      +materialized: view
    marts:
      +materialized: view
flags:
  require_generic_test_arguments_property: true