life_admin_dbt:
  target: "{{ env_var('DBT_TARGET','dev') }}"
  outputs:
    dev:
      type: bigquery
      location: "{{ env_var('DBT_BQ_LOCATION') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      method: service-account
      dataset: ticktick_dbt_dev
      # Use keyfile_json and an environment variable. This is a base64 string NOT a json object
      # how to gen the base64 string: base64 -w 0 bq_sa.json > sa.txt
      keyfile: "./sa.json"
      threads: 16
    prod:
      type: bigquery
      location: "{{ env_var('DBT_BQ_LOCATION') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      method: service-account
      dataset: ticktick_dbt_prod
      keyfile: "./sa.json"
      threads: 16
    CI:
      type: bigquery
      location: "{{ env_var('DBT_BQ_LOCATION') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      method: service-account
      dataset: "{{ env_var('DBT_CI_SCHEMA','ticktick_dbt_ci')}}"
      keyfile: "./sa.json"
      threads: 16

# EL profile to load from data in fetched at runtime
    load_raw:
     type: duckdb
     path: './duckdb.dbt'
     extensions: ['httpfs']
     threads: 16
     secrets:
       - type: s3
         region: asia-southeast1
         key_id: "{{ env_var('GCS_KEY') }}"
         secret: "{{ env_var('GCS_SECRET') }}"
         endpoint: "storage.googleapis.com"
    stage_raw:
      type: bigquery
      location: "{{ env_var('DBT_BQ_LOCATION') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      method: service-account
      # this is just arbitrary value won't get picked up by 
      # the actual dbt macro external table
      dataset: raw 
      keyfile: "./sa.json"
      threads: 16



# ticktick EL profile 
    load_snapshot:
     type: duckdb
     path: './duckdb.dbt'
     extensions: ['httpfs']
     threads: 16
     secrets:
       - type: s3
         region: asia-southeast1
         key_id: "{{ env_var('GCS_KEY') }}"
         secret: "{{ env_var('GCS_SECRET') }}"
         endpoint: "storage.googleapis.com"
    dump_snapshot:
     type: duckdb
     path: './duckdb.dbt'
     extensions: ['httpfs']
     threads: 16
     secrets:
       - type: s3
         region: asia-southeast1
         key_id: "{{ env_var('GCS_KEY') }}"
         secret: "{{ env_var('GCS_SECRET') }}"
         endpoint: "storage.googleapis.com"


elementary:
  target: default
  outputs:
    default:
      type: bigquery
      location: "{{ env_var('DBT_BQ_LOCATION') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      method: service-account
      dataset: ticktick_dbt_prod
      keyfile: "/tmp/sa.json"
      threads: 16