version: 2

models:
  - name: base_projects
    description: "base table containing latest project state pulled from ticktick open API"
    columns:
      - name: project_id
        data_type: string
        description: ""

      - name: name
        data_type: string
        description: ""

      - name: sort_order
        data_type: int64
        description: ""

      - name: group_id
        data_type: string
        description: ""

      - name: kind
        data_type: string
        description: ""

      - name: color
        data_type: string
        description: ""

      - name: view_mode
        data_type: string
        description: ""

      - name: permission
        data_type: string
        description: ""

      - name: closed
        data_type: boolean
        description: ""
  - name: base_tasks
    description: "base table containing latest task state pulled from ticktick open API"
    columns:
      - name: task_id
        data_type: string
        description: ""

      - name: project_id
        data_type: string
        description: ""

      - name: sort_order
        data_type: int64
        description: ""

      - name: title
        data_type: string
        description: ""

      - name: timezone
        data_type: string
        description: ""

      - name: is_allday
        data_type: boolean
        description: ""

      - name: priority
        data_type: int64
        description: ""

      - name: status
        data_type: int64
        description: ""

      - name: tags
        data_type: string
        description: ""

      - name: column_id
        data_type: string
        description: ""

      - name: etag
        data_type: string
        description: ""

      - name: kind
        data_type: string
        description: ""

      - name: repeat_flag
        data_type: string
        description: ""

      - name: start_date
        data_type: timestamp
        description: ""

      - name: due_date
        data_type: timestamp
        description: ""

      - name: reminders
        data_type: string
        description: ""

      - name: completed_time
        data_type: timestamp
        description: ""

      - name: childids
        data_type: string
        description: ""

      - name: parent_id
        data_type: string
        description: ""



  - name: base_projects_snapshot
    description: "project snapshot that gets loaded on short interval to capture completed / deleted projects"
    columns:
      - name: project_id
        data_type: string
        description: ""

      - name: name
        data_type: string
        description: ""

      - name: sort_order
        data_type: int64
        description: ""

      - name: group_id
        data_type: string
        description: ""

      - name: kind
        data_type: string
        description: ""

      - name: color
        data_type: string
        description: ""

      - name: view_mode
        data_type: string
        description: ""

      - name: permission
        data_type: string
        description: ""

      - name: closed
        data_type: boolean
        description: ""

      - name: dbt_scd_id
        data_type: string
        description: ""

      - name: dbt_updated_at
        data_type: timestamp
        description: ""

      - name: dbt_valid_from
        data_type: timestamp
        description: ""

      - name: dbt_valid_to
        data_type: timestamp
        description: ""
  - name: base_tasks_snapshot
    description: "tasks snapshot that gets loaded on short interval to capture completed / deleted tasks"
    columns:
      - name: task_id
        data_type: string
        description: ""

      - name: project_id
        data_type: string
        description: ""

      - name: sort_order
        data_type: int64
        description: ""

      - name: title
        data_type: string
        description: ""

      - name: timezone
        data_type: string
        description: ""

      - name: is_allday
        data_type: boolean
        description: ""

      - name: priority
        data_type: int64
        description: ""

      - name: status
        data_type: int64
        description: ""

      - name: tags
        data_type: string
        description: ""

      - name: column_id
        data_type: string
        description: ""

      - name: etag
        data_type: string
        description: ""

      - name: kind
        data_type: string
        description: ""

      - name: repeat_flag
        data_type: string
        description: ""

      - name: start_date
        data_type: timestamp
        description: ""

      - name: due_date
        data_type: timestamp
        description: ""

      - name: reminders
        data_type: string
        description: ""

      - name: completed_time
        data_type: timestamp
        description: ""

      - name: childids
        data_type: string
        description: ""

      - name: parent_id
        data_type: string
        description: ""


