version: 2
models:
  - name: stg_tasks
    columns:
      - name: task_id
        data_tests:
          - unique
          - not_null
        description: ''
        config:
          meta: {}
          tags: []
      - name: project_id
        description: ''
        config:
          meta: {}
          tags: []
        data_tests:
          - relationships:
              to: ref('stg_projects')
              field: project_id
      - name: sort_order
        description: ''
        config:
          meta: {}
          tags: []
      - name: title
        description: ''
        config:
          meta: {}
          tags: []
      - name: timezone
        description: ''
        config:
          meta: {}
          tags: []
      - name: is_allday
        description: ''
        config:
          meta: {}
          tags: []
      - name: priority
        description: ''
        config:
          meta: {}
          tags: []
      - name: tags
        description: ''
        config:
          meta: {}
          tags: []
      - name: column_id
        description: ''
        config:
          meta: {}
          tags: []
      - name: etag
        description: ''
        config:
          meta: {}
          tags: []
      - name: kind
        description: ''
        config:
          meta: {}
          tags: []
      - name: repeat_flag
        description: ''
        config:
          meta: {}
          tags: []
      - name: start_date
        description: ''
        config:
          meta: {}
          tags: []
      - name: due_date
        description: ''
        config:
          meta: {}
          tags: []
      - name: reminders
        description: ''
        config:
          meta: {}
          tags: []
      - name: childids
        description: ''
        config:
          meta: {}
          tags: []
      - name: parent_id
        description: ''
        config:
          meta: {}
          tags: []
      - name: completed_time
        description: |
          Timestamp when the task was completed / wont do.
          - Inferred from dbt snapshot.
          - Ticktick API do not provide this field (at least not reliably cause it only retrieve new task).
        config:
          meta: {}
          tags: []
      - name: updated_time
        description: |
          inferred updated time; Only available for completed task
          due to ticktick API limitation we had to workaround with
          snapshots.
        config:
          meta: {}
          tags: []
      - name: status
        description: ''
        config:
          meta: {}
          tags: []
      - name: gtd_work_type
        description: |
          optional field indicating if a task was done under
          - shallow work (during clarification) or 
          - deep work (scheduled properly into next action)
        config:
          meta: {}
          tags: []
  - name: stg_projects
    columns:
      - name: project_id
        data_tests:
          - unique
          - not_null
        description: ''
        config:
          meta: {}
          tags: []
      - name: name
        description: ''
        config:
          meta: {}
          tags: []
      - name: sort_order
        description: ''
        config:
          meta: {}
          tags: []
      - name: group_id
        description: ''
        config:
          meta: {}
          tags: []
      - name: kind
        description: ''
        config:
          meta: {}
          tags: []
      - name: color
        description: ''
        config:
          meta: {}
          tags: []
      - name: view_mode
        description: ''
        config:
          meta: {}
          tags: []
      - name: permission
        description: ''
        config:
          meta: {}
          tags: []
      - name: completed_time
        description: |
          Timestamp when the project was closed/archived.
          - Inferred from dbt snapshot.
          - Ticktick API do not provide this field.
        config:
          meta: {}
          tags: []
      - name: closed
        description: ''
        config:
          meta: {}
          tags: []
