name: CD on PR

on:

  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

env:
  # dbt Environment Variables
  DBT_PROFILES_DIR: .
  DBT_TARGET: "prod"
  DBT_BQ_PROJECT: ${{ secrets.DBT_BQ_PROJECT }}
  DBT_BQ_LOCATION: ${{ secrets.DBT_BQ_LOCATION }}
  
  # Google Cloud Storage Environment Variables
  GCS_KEY: ${{ secrets.GCS_KEY }}
  GCS_SECRET: ${{ secrets.GCS_SECRET }}

  # Lightdash Environment Variables
  LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
  LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}
  LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}

  # dbt project yaml env var
  ENABLE_GTD_WORK_TYPE_CATEGORIZATION: ${{ vars.ENABLE_GTD_WORK_TYPE_CATEGORIZATION }}
  GTD_DEEP_WORK_TAGS: ${{ vars.GTD_DEEP_WORK_TAGS }}
  GTD_SHALLOW_WORK_TAGS: ${{ vars.GTD_SHALLOW_WORK_TAGS }}
  DBT_TIMEZONE: ${{ vars.DBT_TIMEZONE }}
  DBT_LOAD_INTERVAL: ${{ vars.DBT_LOAD_INTERVAL }}
  GCS_RAW_BUCKET: ${{ secrets.GCS_RAW_BUCKET }}

permissions:
  contents: write
jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for git diff to work properly
          token: ${{ secrets.GITHUB_TOKEN }} # Required for pushing changes


      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install python deps
        run: uv sync
        
      - name: Decode SA Key
        # This is a more secure way to decode the secret, as it avoids exposing it in the logs.
        run: echo "${{ secrets.DBT_BQ_KEYFILE_JSON }}" | base64 --decode > sa.json


      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Get lightdash version
        id: version
        run: |
          echo "value=$(curl -s "${{ secrets.LIGHTDASH_URL }}/api/v1/health" | jq -r '.results.version')" >> $GITHUB_OUTPUT


      - name: Install npm dependencies
        run: bun install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || bun install -g @lightdash/cli@latest

      - name: dbt deploy
        run: source .venv/bin/activate && dbt deps && dbt build

      - name: Set var DBT_CI_SCHEMA
        run: echo "DBT_CI_SCHEMA=PR_${{ github.event.number }}" >> $GITHUB_ENV

      - name: drop dbt CI schema
        env: 
          DBT_CI_SCHEMA: ${{ env.DBT_CI_SCHEMA }}
        run: source .venv/bin/activate && dbt run-operation drop_ci_schema
      - name: lightdash deploy
        run: source .venv/bin/activate && lightdash deploy -s "life_admin_dbt"

      - name: Upload Lightdash Content
        run: lightdash upload --project ${{ secrets.LIGHTDASH_PROJECT }} --force

      - name: Download Lightdash Content (Post-Upload for Sync)
        run: lightdash download --project ${{ secrets.LIGHTDASH_PROJECT }}

      - name: Download Lightdash exposures
        run: lightdash generate-exposures

      # use force-with-lease to prefer the CD runner's version, 
      # while safely failing if remote has commits other than the runner's.
      - name: Commit back Lightdash content changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lightdash/
          git add models/lightdash_exposures.yml
          git diff --staged --quiet || git commit -m "chore: Sync Lightdash content and exposures from prod [skip ci]"
          git push --force-with-lease
