name: Write back changes on lightdash prod instance to repo.

on:

  workflow_dispatch:


env:
  # Lightdash Environment Variables
  LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
  LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}
  LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}


permissions:
  contents: write
jobs:
  writeback_changes:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for git diff to work properly
          token: ${{ secrets.GITHUB_TOKEN }} # Required for pushing changes

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Get lightdash version
        id: version
        run: |
          echo "version=$(curl -s "${{ secrets.LIGHTDASH_URL }}/api/v1/health" | jq -r '.results.version')" >> $GITHUB_OUTPUT


      - name: Install npm dependencies
        run: bun install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || bun install -g @lightdash/cli@latest

      - name: Download Lightdash Content
        run: lightdash download --project ${{ secrets.LIGHTDASH_PROJECT }}

      # use force-with-lease to prefer the CD runner's version, 
      # while safely failing if remote has commits other than the runner's.
      - name: Commit back Lightdash content changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lightdash/
          git add models/lightdash_exposures.yml
          git diff --staged --quiet || git commit -m "chore: Sync Lightdash content and exposures from prod [skip ci]"
          git push --force-with-lease
