name: Daily dbt job

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

  schedule:
    # runs at 6AM VNT daily
    - cron: 0 23 * * *



jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install python deps
        run: uv sync
        
      - name: Decode SA Key
        # This is a more secure way to decode the secret, as it avoids exposing it in the logs.
        run: echo "${{ secrets.DBT_BQ_KEYFILE_JSON }}" | base64 --decode > sa.json

      - name: Run dbt
        run: uv run dbt deps && uv run dbt run
        env:
          # dbt Environment Variables
          DBT_PROFILES_DIR: .
          DBT_TARGET: "prod"
          DBT_BQ_PROJECT: ${{ secrets.DBT_BQ_PROJECT }}
          DBT_BQ_LOCATION: ${{ secrets.DBT_BQ_LOCATION }}
          
          # Google Cloud Storage Environment Variables
          GCS_KEY: ${{ secrets.GCS_KEY }}
          GCS_SECRET: ${{ secrets.GCS_SECRET }}

          # Lightdash Environment Variables
          LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
          LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}

          # dbt project yaml env var
          ENABLE_GTD_WORK_TYPE_CATEGORIZATION: ${{ vars.ENABLE_GTD_WORK_TYPE_CATEGORIZATION }}
          GTD_DEEP_WORK_TAGS: ${{ vars.GTD_DEEP_WORK_TAGS }}
          GTD_SHALLOW_WORK_TAGS: ${{ vars.GTD_SHALLOW_WORK_TAGS }}
          DBT_TIMEZONE: ${{ vars.DBT_TIMEZONE }}