name: Todoist EL
on:
  workflow_dispatch:
        
  schedule:
    - cron: '0 22-23 * * *'
    - cron: '0 0-16 * * *'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: false


jobs:
  run-EL:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: install project deps 
        run: uv sync

      - name: trigger extraction
        run: uv run EL/todoist/fetch_todoist.py
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          
      - name: Dump extracted data to GCS 🪣
        run: uv run dbt build
        env:
          DBT_PROFILES_DIR: .
          GCS_KEY: ${{ secrets.GCS_KEY }}
          GCS_SECRET: ${{ secrets.GCS_SECRET }}
          DBT_TARGET: "load_raw"

